require 'addressable/uri'
require 'cloudera/configuration'
require 'cloudera/entity'
require 'cloudera/entity/uri'
require 'cloudera/language'
require 'cloudera/rest/client'
require 'cloudera/settings'
require 'cloudera/user'
